// svelte/src/components/ProductList.svelte
<script>
 import { gql } from '@apollo/client/core';
 import { query } from "svelte-apollo";
import ProductItem from "./ProductItem.svelte"


 const GET_PRODUCTS = gql`
  query GetProducts{
    products {
      id
      name
      brand
      price
      img
  }
}`;

  const products = query(GET_PRODUCTS);

</script>

<style>
  #productList{
    margin: 2em;
    display: flex;
    gap: 2ch;

  }
</style>


{#if $products.loading}
  Loading...
{:else if $products.error}
  Error: {$products.error.message}
{:else}
<div id="productList">
  {#each $products.data.products as product}
    <ProductItem product={product}/>
  {/each}
</div>  
{/if}

// b2b/src/components/ProductList.jsx
import React from "react";
import { useQuery } from "@apollo/client";
import {GET_PRODUCTS} from "../gql/queries"
import ProductListItem from "./ProductListItem";

export default function ProductList(){
  const { loading, error, data } = useQuery(GET_PRODUCTS);
  if (loading) return <p>Loading...</p>;
  if (error) return <p>{error.message}</p>;

  
  return <div style={{
    margin: "2em",
    display: "flex",
    gap: "2ch"
  }}>{data?.products.map((product) => <ProductListItem product={product} key={product.id}/>)}</div>;
}
